### ISSUE TITLE
JsonReader should not attempt accessing Stream.Position and Stream.Length

### ISSUE THREAD

**Issue by jpmikkers** [Mimetis/JsonExtensions#2]
A stream coming from a socket or pipe or similar is not seekable and has unknown length. JsonReader should use the result of Stream.Read to determine if the last block was reached.

**Comment by Mimetis** [comment]
Good catch !

It's already the case (Well if I'm not wrong)
I think removing the checks on `Position` / `Length` should not be a big deal (imo)
